--- 
slug: updated-applications
permalink: http://www.wezm.net/2010/01/updated-applications/
kind: article
section: technical
created_at: 2010-01-09 07:17:24
title: Updated Applications
post_id: 277
tags: 
- appzapper
- disco
- software
- updates
- xtorrent
categories: 
- Mac OS X
- Software
status: publish
