---
slug: updated-applications
permalink: http://www.wezm.net/2010/01/updated-applications/
kind: article
section: technical
created_at: 2010-01-09 18:17:24.000000000 +11:00
title: Updated Applications
post_id: 277
tags:
- appzapper
- disco
- software
- updates
- xtorrent
categories:
- Mac OS X
- Software
status: publish
extra: A follow up to, "Update Expectations", in which I check in on some neglected
  apps.
short_url: http://bit.ly/bstq0a
